name: Compilator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mkdir /opt/config
        touch /opt/config/configv2.properties
        mvn -B package --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: target

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: package
    
    - name: config copy files
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts
        
    - name: Deploy to production
      run: |
        echo "${{ secrets.KEY }}" > ./private_key
        chmod 600 ./private_key
        scp -o StrictHostKeyChecking=no -i ./private_key -r target ${{ secrets.USER }}@${{ secrets.SERVER }}:/opt/bot
